"""Contrato do repositorio de estado operacional.

Nem tudo precisa ser compartilhado entre instancias:

* Topologia da maquete  -> vem do seed, deterministica, cada instancia recria.
* Espelho do JACAD      -> vem do sync periodico, cada instancia recarrega.
* Alocacao de carteiras -> funcao pura de (ordem das cadeiras, lista da turma).
* Aulas em janela       -> derivada do relogio + grade horaria.

O que sobra - e o que este contrato cobre - e o estado que muda a cada
passagem de catraca e precisa ser visto por todas as instancias:
presencas, quem esta no campus, feed, alertas, serie do dia e contadores.
"""
from __future__ import annotations

from typing import Any, Awaitable, Callable, Dict, List, Optional, Protocol, Set

from app.models.academico import RegistroPresenca
from app.models.dashboard import Alerta

CANAL_EVENTOS = "insted:campus:eventos"


class EstadoStore(Protocol):
    """Operacoes de estado compartilhado. Toda implementacao e assincrona."""

    # -- ciclo de vida ------------------------------------------------------
    async def iniciar(self) -> None: ...
    async def encerrar(self) -> None: ...

    @property
    def nome(self) -> str: ...

    # -- abertura de aula ---------------------------------------------------
    async def marcar_aula_aberta(self, aula_id: str) -> bool:
        """Marca a aula como aberta. Devolve True apenas para quem ganhou.

        Duas instancias podem detectar a mesma aula entrando na janela de
        chegada no mesmo instante; so uma deve criar os registros de presenca.
        """
        ...

    async def aula_esta_aberta(self, aula_id: str) -> bool: ...
    async def aulas_abertas(self) -> Set[str]: ...
    async def fechar_aula(self, aula_id: str) -> None: ...

    # -- presencas ----------------------------------------------------------
    async def salvar_presencas(self, aula_id: str, registros: List[RegistroPresenca]) -> None: ...
    async def obter_presenca(self, aula_id: str, ra: str) -> Optional[RegistroPresenca]: ...
    async def atualizar_presenca(self, registro: RegistroPresenca) -> None: ...
    async def presencas_da_aula(self, aula_id: str) -> List[RegistroPresenca]: ...
    async def presencas_do_aluno(self, ra: str) -> List[RegistroPresenca]: ...

    # -- presenca fisica no campus -----------------------------------------
    async def entrar_campus(self, ra: str) -> None: ...
    async def sair_campus(self, ra: str) -> None: ...
    async def esta_no_campus(self, ra: str) -> bool: ...
    async def alunos_no_campus(self) -> Set[str]: ...
    async def total_no_campus(self) -> int: ...

    # -- feed de passagens --------------------------------------------------
    async def push_evento(self, evento: dict) -> None: ...
    async def feed(self, limite: int = 30) -> List[dict]: ...

    # -- alertas ------------------------------------------------------------
    async def push_alerta(self, alerta: Alerta, chave_dedupe: str) -> bool:
        """Grava o alerta. Devolve False se a chave ja foi emitida."""
        ...

    async def alertas(self, limite: int = 20) -> List[Alerta]: ...
    async def limpar_dedupe(self, prefixo: str) -> None: ...

    # -- serie intradiaria --------------------------------------------------
    async def salvar_ponto_serie(self, hora: str, ponto: dict) -> None: ...
    async def serie(self) -> List[dict]: ...

    # -- contadores e catracas ---------------------------------------------
    async def incrementar_passagem(self, catraca_id: str, entrada: bool, momento: str) -> None: ...
    async def estado_catracas(self) -> Dict[str, dict]: ...
    async def marcar_catraca_offline(self, catraca_id: str) -> None: ...
    async def contadores(self) -> Dict[str, int]: ...

    # -- relogio de demonstracao -------------------------------------------
    async def ancora_relogio(self) -> Optional[str]: ...
    async def definir_ancora_relogio(self, iso: str) -> None: ...

    # -- difusao entre instancias ------------------------------------------
    async def publicar(self, payload: Any) -> None:
        """Envia para todas as instancias, inclusive a que publicou."""
        ...

    async def assinar(self, callback: Callable[[Any], Awaitable[None]]) -> None:
        """Escuta o canal e chama `callback` a cada mensagem de outra instancia."""
        ...
